### ISSUE TITLE
As a forgetful user I want to add a person's photo so that I can remember a person's face.

### ISSUE THREAD

**Issue by cjianhui** [CS2103AUG2017-W09-B4/main#31]

**Comment by cjianhui** [comment]
- padd [p/PERSON INDEX] [PATH] (Overwrites original photo)
[pa]
- premove [p/PERSON INDEX] [PATH] 
[pr]

**Comment by nassy93** [comment]
Revised to
- ppset [p/PERSON INDEX] [PATH] (Overwrites any set photo)
[pps]
- ppreset [p/PERSON INDEX]
[ppr]
