### ISSUE TITLE
[Acceptance Testing] Acceptance testing for pre-release

### ISSUE THREAD

**Issue by charlesgohck** [CS2103AUG2017-W09-B4/main#77]

**Comment by charlesgohck** [comment]
1. UI looks slick
<img width="1478" alt="screen shot 2017-11-03 at 3 11 41 pm" src="https://user-images.githubusercontent.com/15852016/32363290-93c29b24-c0a9-11e7-96f0-a6c31eeb632f.png">
2. Grouping works very well
<img width="1478" alt="screen shot 2017-11-03 at 3 21 02 pm" src="https://user-images.githubusercontent.com/15852016/32363507-a79cc790-c0aa-11e7-96a2-dd8f62d827a5.png">

**Suggestions:**
1. How about additional ability to add even without listing first. Currently if I don't list it will break.

**Comment by nassy93** [comment]
with regards to the suggestion... that is impossible because even the default code works by finding the person via the listed index so changing it would require quite an overhaul to the application at this point
