### ISSUE TITLE
Acceptance Testing

### ISSUE THREAD

**Issue by cctdaniel** [CS2103AUG2017-W09-B4/main#78]
Issue #1: `find` initials not working
<img width="1792" alt="screen shot 2017-11-03 at 2 59 33 pm" src="https://user-images.githubusercontent.com/26521733/32362929-9e88fa82-c0a7-11e7-999d-db4e45ed1a99.png">
<img width="1792" alt="screen shot 2017-11-03 at 3 00 03 pm" src="https://user-images.githubusercontent.com/26521733/32362939-b0d15dc4-c0a7-11e7-8b1b-d5983747bcc5.png">

Issue #2: user guide states that the `select` command will load Google search page but it's currently not doing that
<img width="717" alt="screen shot 2017-11-03 at 3 03 43 pm" src="https://user-images.githubusercontent.com/26521733/32363042-3735ee2a-c0a8-11e7-8933-173625dc5279.png">
<img width="1792" alt="screen shot 2017-11-03 at 3 02 36 pm" src="https://user-images.githubusercontent.com/26521733/32363010-0dde5558-c0a8-11e7-8adc-28eafee51dbf.png">

Issue #3: `fadd` and `fremove` command not working
<img width="1792" alt="screen shot 2017-11-03 at 3 05 12 pm" src="https://user-images.githubusercontent.com/26521733/32363092-7bdceb1e-c0a8-11e7-915a-a34b260d1e9f.png">
<img width="1792" alt="screen shot 2017-11-03 at 3 06 56 pm" src="https://user-images.githubusercontent.com/26521733/32363129-a61bb61c-c0a8-11e7-8c73-c4e95326b96b.png">

Issue #4: `gadd` and `gremove` command not working
<img width="1792" alt="screen shot 2017-11-03 at 3 08 08 pm" src="https://user-images.githubusercontent.com/26521733/32363165-dea96b64-c0a8-11e7-9132-25276a58a6cb.png">
<img width="1792" alt="screen shot 2017-11-03 at 3 08 56 pm" src="https://user-images.githubusercontent.com/26521733/32363180-efd07c20-c0a8-11e7-8754-8fef24fd4626.png">

**Comment by nassy93** [comment]
You might have downloaded and tested Bamboo V1.2 by accident. That version does not have those commands implemented hence the reasons why the commands were unknown and not working

**Comment by cctdaniel** [comment]
I redownloaded the released jar file and confirmed that it was the 1.3 version and it still doesn't work.

**Comment by nassy93** [comment]
I checked that Issue #1, #3 and #4 are working in V1.4. Issue #2 has been fixed as that part of the user guide was old info. fadd and fremove should be working since v1.2 though. I'm not sure why they're not working on your end.

**Comment by cctdaniel** [comment]
As long as it works on your end it should be fine I guess.
