### ISSUE TITLE
ppset instructions for mac? Using mac-style filepaths doesn't seem to work

### ISSUE THREAD

**Issue by bokwoon95** [CS2103AUG2017-W09-B4/main#79]
I've got a .png file that called bryan.png in my Downloads folder, but this command
```ppset 1 fp/~/Downloads/bryan.png```
warns me that ```File at given file path was not type .png```

**Comment by nassy93** [comment]
It appears that our file type detection function, Files.probeContentType appears to be buggy on MacOS and returns a null. Thank you for the report, we will attempt to fix the bug
