### ISSUE TITLE
Elaboration on what 'cadd' does

### ISSUE THREAD

**Issue by bokwoon95** [CS2103AUG2017-W09-B4/main#80]
The docs mentions that ```Adds a person’s Google Calendar events to schedules.``` but after running 
```cadd p/1 i/bokwoon.c@gmail.com```
nothing seems to happen. Perhaps you can elaborate on what should work?

**Comment by nassy93** [comment]
There was a little problem with the handling of the id. We have found the issue and fixed it. Thank you for the report. :)
